/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lambdalib2_vis_editor_ImGui */

#ifndef _Included_cn_lambdalib2_vis_editor_ImGui
#define _Included_cn_lambdalib2_vis_editor_ImGui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lambdalib2_vis_editor_ImGui
 * Method:    begin
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_lambdalib2_vis_editor_ImGui_begin
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     cn_lambdalib2_vis_editor_ImGui
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_lambdalib2_vis_editor_ImGui_end
  (JNIEnv *, jclass);

/*
 * Class:     cn_lambdalib2_vis_editor_ImGui
 * Method:    text
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_lambdalib2_vis_editor_ImGui_text
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
